from flask import Flask , render_template
from games import Games

app = Flask(__name__)


minecraft = Games(id = 1  ,img ="img/catalagoGames/minecraft.jpeg" , banner="img/games/game-minecraft.jpg", nome = "minecraft" ,desenvolvedor="Markus Persson" , ano = "18 de nov de 2011", 
                estilo = " Sandbox e Sobrevivência " , tempo="12h" , plataforma="Microsoft Windows, macOS, Linux e alguns dispositivos móveis",
                resumo= "Minecraft é um jogo eletrônico sandbox de sobrevivência criado por Markus Notch Persson e desenvolvido pela Mojang Studios, adquirida pela Microsoft em 2014. Lançado em 2009, tornou-se o jogo mais vendido de todos os tempos, com mais de 300 milhões de cópias vendidas até 2023. Os jogadores exploram um mundo tridimensional pixelizado, extraem recursos, constroem estruturas e podem combater inimigos ou interagir com outros jogadores.  Os modos de jogo incluem sobrevivência, onde os jogadores devem adquirir recursos para sobreviver, e criativo, com recursos ilimitados. Mods na versão Java permitem modificações na jogabilidade. O jogo recebeu aclamação da crítica e é considerado um dos melhores jogos eletrônicos de todos os tempos.Minecraft influenciou a cultura popular, gerando redes sociais, paródias e convenções. Além disso, é usado em educação, permitindo a construção de ambientes virtuais e dispositivos de hardware. Títulos spin-off incluem Minecraft: Story Mode, Minecraft Earth, Minecraft Dungeons e Minecraft Legends. Com sua criatividade ilimitada e jogabilidade cativante, Minecraft continua a ser um fenômeno global.")

fallout4 = Games(id = 2  ,img ="img/catalagoGames/fallout4.jpeg" ,banner="img/games/fallout4-banner.png", nome = "Fallout 4" , desenvolvedor="Bethesda Game Studios", ano = "10 de nov de 2015", 
                estilo = "RPG e RetroFuturista" , tempo="27 horas" , plataforma="Xbox One, PlayStation 4 e PC",
                resumo= "No começo de Fallout 4, temos a oportunidade de vivenciar algo inédito na franquia: uma vida antes das bombas nucleares caírem. Em 2077, podemos escolher se vamos jogar no papel de Nate ou Nora (nomes padrão dos personagens no game), o par que está a aproveitando a vida de casado e cuidando do recém nascido Shaun. Um adorável dia do casal é interrompida por um representante da Vault-Tec, uma empresa responsável por construir refúgios subterrâneos por todo o país no caso de uma guerra nuclear.Fallout 4 se passa apenas 9 anos antes dos eventos da série da Amazon PrimeFallout 4 se passa apenas 9 anos antes dos eventos da série da Amazon PrimeFonte:  Bethesda/Reprodução Pelos serviços militares prestados por sua família no passado, o representante veio apenas avisar que vocês foram pré-selecionados para o abrigo 111, que fica bem perto da sua casa. Tudo o que é necessário é assinar alguns papéis e ficar com a consciência tranquila de que, caso preciso, o abrigo estará lá os aguardando.A má notícia é que não demora nada para que esse abrigo seja necessário, já que a TV passa a noticiar que bombas nucleares estão caindo por todo o território americano. Em desespero, a família se dirige rapidamente ao abrigo 111, escapando por pouco dos efeitos da bomba nuclear que cai por perto segundos antes de descermos às profundezas da construção da Vault-Tec.Lá dentro, recebemos nosso uniforme azul e somos dirigidos para uma câmara que deveria apenas nos descontaminar e despressurizar, mas que nos congela sem aviso prévio.")

valorant = Games(id = 3  ,img ="img/catalagoGames/valorant.jpeg" ,banner="img/games/valorant-banner.jpg", nome = "Valorant ",desenvolvedor="Riot Games" , ano = " 2 de junho de 2020", 
                estilo = "FPS tático" , tempo="Varias Horas" , plataforma="exclusivamente no PC",
                resumo= "Valorant é um jogo gratuito do gênero FPS desenvolvido pela Riot Games, estúdio norte-americano que ficou conhecido pelo aclamado MOBA League of Legends. O game de tiro é bem parecido com Counter-Strike: Global Offensive, o mais famoso do segmento, mas se diferencia em alguns aspectos. Os personagens, por exemplo, são únicos e possuem habilidades próprias. Portanto, não se trata apenas de armas. Lançado oficialmente em junho de 2020, Valorant pode ser jogado apenas no PC. O título já é um sucesso e certamente entrará com força no cenário dos esportes eletrônicos.Regras do Valorant . regras do valorant No Valorant, os duelos ocorrem no formato 5×5 No Valorant, dois times de cinco integrantes se enfrentam no mapa. A dinâmica funciona no esquema “ataque x defesa” e cada personagem tem apenas uma vida durante o round. Vence a partida o time que anotar 13 pontos primeiro (em 25 possíveis). O round tem duração de 1:40 minutos. Neste meio tempo, as equipes podem se equipar com armas e habilidades especiais para enfrentar os adversários. Tudo gira em torno de uma pequena bomba chamada “spike”. Ela pode ser plantada ou desativada. Sendo assim, o quinteto que estiver atacando vence o round caso: \n Elimine todos os adversários antes do tempo acabar ou\nConsiga plantar e detonar a spike na base inimiga\nDo outro lado, o quinteto que estiver defendendo vence o round caso:\nElimine todos os adversários antes do tempo acabar ou\nSobreviva até o final sem que a spike seja plantada ou\nDesarme a spike (caso ela seja plantada)\nOs personagens possuem 100 pontos de vida. É possível abatê-los tanto com armamentos quanto habilidades. Cada arma ou skill tira uma quantia específica de dano.\nEconomia no Valorant o que é valorant Administre seus recursos para comprar armas e skills Assim como no CS:GO, Valorant tem um sistema único de economia. É necessário ter “créditos” para comprar armas e habilidades no início dos rounds. Cada equipe começa o jogo com 800 créditos. Essa quantia pode se incrementada através de diversas maneiras. Se liga:\nAbater um adversário: 200 créditos para o jogador\nPlantar spike: 300 créditos para todos do time\nDesarmar spike: 300 créditos para o jogador\nPerder um round: 1.900~2.900 créditos para todos do time\nGanhar um round: 3.000 créditos para todos do time\n“Eu ganho crédito até quando perco round?”, você deve estar se perguntando. Sim, ganha! Esse método de bonificação é necessário para que a equipe que estiver perdendo também tenha chances de se recuperar na partida. Senão seria uma grande bola de neve! Quanto mais rounds seguidos um time perder, mais créditos ele receberá. O valor começa em 1.900 (mínimo) e pode chegar até 2.900 (máximo). Valorant é bem estratégico nesse sentido. É preciso lidar com as finanças para não sair fazendo bobagem. No caso, você terá que levar em conta a economia de todos os seus companheiros para assim orquestrar as melhores compras.")
fortnite = Games(id = 4  ,img ="img/catalagoGames/fortnite.jpeg" ,banner="img/games/fortnite-banner.jpg", nome = "Fortnite",desenvolvedor="Epic Games" , ano = "26 de set de 2017", 
                estilo = "Battle Royale" , tempo="30 minutos" , plataforma="PC, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, dispositivos Android e iOS e Nintendo Switch",
                resumo= "Fortnite é um jogo eletrônico multijogador online que possui diferentes modos de jogo que compartilham a mesma jogabilidade e motor gráfico12. O jogo é baseado em sobrevivência, cooperação e construção de estruturas34. O modo mais popular é o Battle Royale, onde 100 jogadores competem para ser o último sobrevivente em uma ilha2. O jogo é desenvolvido pela Epic Games e pode ser jogado de graça em diversas plataformas")
theWither = Games(id = 5  ,img ="img/catalagoGames/theWither.png" ,banner="img/games/theWither3-banner.jpg", nome = "The Wither 3:Wild Hunt",desenvolvedor="CD Projekt RED" , ano = "19 de mai de 2015", 
                estilo = "RPG de ação" , tempo="52 horas" , plataforma="Microsoft Windows, PlayStation 4, Xbox One e  Nintendo Switch",
                resumo= "Lançado em 2015, The Witcher 3: Wild Hunt marcou época como um dos jogos mais aclamados da geração. Ele conta a aventura do bruxo Geralt de Rívia em busca da sua filha, Ciri, enquanto enfrenta inimigos mortais e explora um mundo cheio de possibilidades, desafios e aventuras1. Ambientado em um gigantesco cenário medieval que dá liberdade total ao jogador, o game, que possui uma jogabilidade não linear e é jogado através de uma perspectiva em terceira pessoa, tem o lendário bruxo Geralt de Rívia como seu protagonista. Geralt inicia uma longa jornada pelos Reinos do Norte enquanto a ordem planetária enfrenta uma grande mudança, com o misterioso e macabro exército de cavaleiros vermelhos conhecido como a “Caçada Selvagem” deixando somente sangue e ruína por onde passa. O jogador terá de enfrentar diversos perigos, usando espadas e magia num mundo em crise, à medida que interage com outros personagens e completa missões para o progresso da história, podendo viajar a pé, a barco, ou montado em Carpeado, o cavalo inseparável de Geralt. The Witcher 3: Wild Hunt foi amplamente aclamado pela crítica, com alguns considerando-no como um dos melhores jogos de todos os tempos. Sua consagração veio na noite de 3 de dezembro de 2015, quando foi galardoado com o grande prêmio de Jogo do Ano na cerimônia de condecoração The Game Awards, considerada a mais importante e prestigiada do ramo dos videogames. The Witcher 3: Wild Hunt é um dos jogos mais premiados da história, com 257 prêmios de múltiplas publicações e eventos recebidos apenas na categoria de melhor jogo. Também foi um sucesso financeiro, tendo vendido cerca de 50 milhões de cópias ao redor do mundo, tornando-se um dos jogos mais vendidos de todos os tempos2.")
assassins_origins = Games(id = 6  ,img ="img/catalagoGames/assassins-creed-origins.jpg" ,banner="img/games/assasinsOrigins-banner.jpg", nome = "Assassins Creed Origins",desenvolvedor="Ubisoft Montreal" , ano = "27 de out de 2017", 
                estilo = "ação e RPG" , tempo="84 horas" , plataforma="PC . PlayStation 4 e Xbox One",
                resumo= "Enredo: O jogo segue Bayek de Siuá, um dos últimos Medjai do Egito, e sua busca por vingança contra a Ordem dos Anciões, um grupo misterioso que busca controlar o Egito e estabelecer uma sociedade onde as massas são subjugadas e a ordem prevalece. Um ano antes dos eventos de Origins, o filho pequeno de Bayek, Khemu, é morto pelos membros da Ordem quando eles tentam interrogar Bayek sobre uma câmara misteriosa em Siuá, seu vilarejo natal. Enfurecido, Bayek trilha um caminho de vingança ao lado de sua esposa Aya, que também está envolvida em um plano para derrubar o Faraó opressivo e incompetente Ptolemeu XIII e colocar Cleópatra no poder. Bayek percorre o Egito, libertando suas cidades e nomos dos membros da Ordem que os governam, e se envolve em eventos como a Guerra Civil Alexandrina, quando Júlio César invade o Egito1. Jogabilidade: Navegação e mapa: O mapa de Origins é composto pelo Baixo Egito e pelo leste da Líbia, e pode ser livremente explorado sem nenhuma tela de carregamento. As cidades principais incluem Gizé, Mênfis, Cirene e Alexandria. Senu, a águia domesticada de Bayek, serve como a nova forma de Visão de Águia, podendo sobrevoar áreas, detectar e marcar inimigos, localizar coletáveis e encontrar passagens secretas. Elementos de RPG: O jogo adota um estilo RPG com um combate mais focado e difícil, além de uma customização mais profunda. Combate: Bayek utiliza uma variedade de armas, incluindo espadas, arcos e escudos, para enfrentar inimigos e membros da Ordem. Irmandade dos Assassinos: É neste jogo que a famosa e oculta Irmandade dos Assassinos tem seu início, com Bayek e seus aliados lutando contra a tirania e a corrupção no Egito Antigo2. Assassin’s Creed: Origins oferece uma experiência imersiva no Egito Antigo, repleta de intrigas, vingança e a origem da lendária Irmandade dos Assassinos.")
            
games_catalogo = [minecraft , fallout4, valorant ,fortnite ,assassins_origins ,theWither ]

@app.route('/')
def home():

    return render_template('historia-games.html')

@app.route('/Catalago-Games')
def catalago_games():
    return render_template('catalogo-games.html', games = games_catalogo)

@app.route('/games/<int:id>')
def games(id:int):
    for game_do_catalogo in games_catalogo:
        if game_do_catalogo.id == id:
            return render_template("games.html", game= game_do_catalogo)






if __name__ in "__main__":
    app.run(debug=True)